apiVersion: v1
kind: Secret

metadata:
  name: chatapp-secrets
  namespace: chat-app

type: Opaque
data:
  jwt: MGM5MGNjYjJjMWNiYWQ1ZjRjZWU4NWMyNGNjM2VjOTE0NDc0ZWVhMGViMTM1ZmEzMjA5MTE2YjYyMmJiZjdhOA==